//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationEng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationEng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Practice.Localization.LocalizationEng", typeof(LocalizationEng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to perform this operation..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All lead list is incorrect..
        /// </summary>
        internal static string AllLeadListIsIncorrect {
            get {
                return ResourceManager.GetString("AllLeadListIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create empty lead list..
        /// </summary>
        internal static string CanNotCreateEmptyLeadList {
            get {
                return ResourceManager.GetString("CanNotCreateEmptyLeadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete call center while eist reconciliation or reports..
        /// </summary>
        internal static string CanNotDeleteCallCenter {
            get {
                return ResourceManager.GetString("CanNotDeleteCallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete LeadList created by other users..
        /// </summary>
        internal static string CannotDeleteLeadListCreatedByOtherUsers {
            get {
                return ResourceManager.GetString("CannotDeleteLeadListCreatedByOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete LeadList created week ago..
        /// </summary>
        internal static string CannotDeleteLeadListCreatedWeekAgo {
            get {
                return ResourceManager.GetString("CannotDeleteLeadListCreatedWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete list..
        /// </summary>
        internal static string CanNotDeleteList {
            get {
                return ResourceManager.GetString("CanNotDeleteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not download lead list while status wait for verification..
        /// </summary>
        internal static string CanNotDownloadLeadListWhileStatusWaitForVerification {
            get {
                return ResourceManager.GetString("CanNotDownloadLeadListWhileStatusWaitForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find this status in system: {0}..
        /// </summary>
        internal static string CannotFindThisStatus {
            get {
                return ResourceManager.GetString("CannotFindThisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update system user..
        /// </summary>
        internal static string CanNotUpdateSystemUser {
            get {
                return ResourceManager.GetString("CanNotUpdateSystemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required..
        /// </summary>
        internal static string CommentIsRequired {
            get {
                return ResourceManager.GetString("CommentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is incorrect..
        /// </summary>
        internal static string DateIsIncorrect {
            get {
                return ResourceManager.GetString("DateIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest name or urls are empty..
        /// </summary>
        internal static string EmptyInterestPart {
            get {
                return ResourceManager.GetString("EmptyInterestPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum does not contais such option..
        /// </summary>
        internal static string EnumNotAllowedValue {
            get {
                return ResourceManager.GetString("EnumNotAllowedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such email is already exist..
        /// </summary>
        internal static string ErrorExistingEmail {
            get {
                return ResourceManager.GetString("ErrorExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректное расширение файла..
        /// </summary>
        internal static string FileExtensionIsIncorrect {
            get {
                return ResourceManager.GetString("FileExtensionIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is incorrect..
        /// </summary>
        internal static string IdIsIncorrect {
            get {
                return ResourceManager.GetString("IdIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest is not found..
        /// </summary>
        internal static string InterestIsNotFound {
            get {
                return ResourceManager.GetString("InterestIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Limit Exceeded..
        /// </summary>
        internal static string InterestsLimit {
            get {
                return ResourceManager.GetString("InterestsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data source type..
        /// </summary>
        internal static string InvalidPhoneBaseDataSourceType {
            get {
                return ResourceManager.GetString("InvalidPhoneBaseDataSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user role..
        /// </summary>
        internal static string InvalidUserRole {
            get {
                return ResourceManager.GetString("InvalidUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not found..
        /// </summary>
        internal static string ItemIsNotFound {
            get {
                return ResourceManager.GetString("ItemIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead list already approved..
        /// </summary>
        internal static string LeadListAlreadyApproved {
            get {
                return ResourceManager.GetString("LeadListAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead list is empty..
        /// </summary>
        internal static string LeadListIsEmpty {
            get {
                return ResourceManager.GetString("LeadListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is null or empty..
        /// </summary>
        internal static string MessageIsNullOrEmpty {
            get {
                return ResourceManager.GetString("MessageIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is invalid..
        /// </summary>
        internal static string ModelIsInvalid {
            get {
                return ResourceManager.GetString("ModelIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordRequiresDigit: Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;).,PasswordTooShort: Passwords must be at least 6 characters., PasswordRequiresNonAlphanumeric: Passwords must have at least one non alphanumeric character., PasswordRequiresLower: Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)., PasswordRequiresUpper: Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        internal static string PasswordValidationError {
            get {
                return ResourceManager.GetString("PasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors ocured during handling of phone database..
        /// </summary>
        internal static string PhoneDatabaseHandlingError {
            get {
                return ResourceManager.GetString("PhoneDatabaseHandlingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel numbers file is incorrect, pixel or site url occurs more than once..
        /// </summary>
        internal static string PixelNumbersFileIsIncorrect {
            get {
                return ResourceManager.GetString("PixelNumbersFileIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is not found..
        /// </summary>
        internal static string ProjectIsNotFound {
            get {
                return ResourceManager.GetString("ProjectIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Limit Exceeded..
        /// </summary>
        internal static string ProjectsLimit {
            get {
                return ResourceManager.GetString("ProjectsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider is not found..
        /// </summary>
        internal static string ProviderIsNotFound {
            get {
                return ResourceManager.GetString("ProviderIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Limit Exceeded..
        /// </summary>
        internal static string ProvidersLimit {
            get {
                return ResourceManager.GetString("ProvidersLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro data url is not specified. Please, fill it and try again..
        /// </summary>
        internal static string RetroDataUrlIsNullOrEmpty {
            get {
                return ResourceManager.GetString("RetroDataUrlIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Limit Exceeded..
        /// </summary>
        internal static string StatusesLimit {
            get {
                return ResourceManager.GetString("StatusesLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error status is empty..
        /// </summary>
        internal static string StatusIsEmpty {
            get {
                return ResourceManager.GetString("StatusIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interes with such name is already exist..
        /// </summary>
        internal static string SuchInterestNameIsAlreadyExist {
            get {
                return ResourceManager.GetString("SuchInterestNameIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity can not be negative..
        /// </summary>
        internal static string TheQuantityCanNotBeNegative {
            get {
                return ResourceManager.GetString("TheQuantityCanNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function is outdated and not working..
        /// </summary>
        internal static string ThisFunctionIsOutdatedAndNotWorking {
            get {
                return ResourceManager.GetString("ThisFunctionIsOutdatedAndNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up bound bigger than down bound..
        /// </summary>
        internal static string UpBoundBiggerThanDownBound {
            get {
                return ResourceManager.GetString("UpBoundBiggerThanDownBound", resourceCulture);
            }
        }
    }
}
