//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationRu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Practice.Localization.LocalizationRu", typeof(LocalizationRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет прав для выполнения данной операции..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все выборки некорректны..
        /// </summary>
        internal static string AllLeadListIsIncorrect {
            get {
                return ResourceManager.GetString("AllLeadListIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно создать выборку, потому что в базе нет номеров для включения в нее. Дождитесь поступления данных от поставщиков..
        /// </summary>
        internal static string CanNotCreateEmptyLeadList {
            get {
                return ResourceManager.GetString("CanNotCreateEmptyLeadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить КЦ, так как есть загруженые отчеты или сверки..
        /// </summary>
        internal static string CanNotDeleteCallCenter {
            get {
                return ResourceManager.GetString("CanNotDeleteCallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете удалить выборку созданную другим пользователем..
        /// </summary>
        internal static string CannotDeleteLeadListCreatedByOtherUsers {
            get {
                return ResourceManager.GetString("CannotDeleteLeadListCreatedByOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить выборку созданную больше недели назад..
        /// </summary>
        internal static string CannotDeleteLeadListCreatedWeekAgo {
            get {
                return ResourceManager.GetString("CannotDeleteLeadListCreatedWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить выборку..
        /// </summary>
        internal static string CanNotDeleteList {
            get {
                return ResourceManager.GetString("CanNotDeleteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя скачать не подтвержденную выборку..
        /// </summary>
        internal static string CanNotDownloadLeadListWhileStatusWaitForVerification {
            get {
                return ResourceManager.GetString("CanNotDownloadLeadListWhileStatusWaitForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалость найти такой статус в системе: {0}..
        /// </summary>
        internal static string CannotFindThisStatus {
            get {
                return ResourceManager.GetString("CannotFindThisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка, нельзя изменять системного пользователя..
        /// </summary>
        internal static string CanNotUpdateSystemUser {
            get {
                return ResourceManager.GetString("CanNotUpdateSystemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется комментарий..
        /// </summary>
        internal static string CommentIsRequired {
            get {
                return ResourceManager.GetString("CommentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата задана некорректно..
        /// </summary>
        internal static string DateIsIncorrect {
            get {
                return ResourceManager.GetString("DateIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали электронный почтовый ящик..
        /// </summary>
        internal static string EmailIsEmpty {
            get {
                return ResourceManager.GetString("EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Названия .
        /// </summary>
        internal static string EmptyInterestPart {
            get {
                return ResourceManager.GetString("EmptyInterestPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перечисление не содержит таких вариантов опций..
        /// </summary>
        internal static string EnumNotAllowedValue {
            get {
                return ResourceManager.GetString("EnumNotAllowedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким электронным почтовым ящиком уже зарегистрирован..
        /// </summary>
        internal static string ErrorExistingEmail {
            get {
                return ResourceManager.GetString("ErrorExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное расширение файла..
        /// </summary>
        internal static string FileExtensionIsIncorrect {
            get {
                return ResourceManager.GetString("FileExtensionIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл, который вы патаетесь загрузить, пуст..
        /// </summary>
        internal static string FileIsNull {
            get {
                return ResourceManager.GetString("FileIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректно задан идентификатор..
        /// </summary>
        internal static string IdIsIncorrect {
            get {
                return ResourceManager.GetString("IdIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали неверный формат электронного почтового ящика..
        /// </summary>
        internal static string IncorrectEmailFormat {
            get {
                return ResourceManager.GetString("IncorrectEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали некорректное имя файла..
        /// </summary>
        internal static string IncorrectFileName {
            get {
                return ResourceManager.GetString("IncorrectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали неверный формат телефонного номера..
        /// </summary>
        internal static string IncorrectPhoneNumberFormat {
            get {
                return ResourceManager.GetString("IncorrectPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интерес не найден..
        /// </summary>
        internal static string InterestIsNotFound {
            get {
                return ResourceManager.GetString("InterestIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен лимит сайтов..
        /// </summary>
        internal static string InterestsLimit {
            get {
                return ResourceManager.GetString("InterestsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы пытаетесь загрузить файл с некорректным расширением..
        /// </summary>
        internal static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указан некорректный источник данных..
        /// </summary>
        internal static string InvalidPhoneBaseDataSourceType {
            get {
                return ResourceManager.GetString("InvalidPhoneBaseDataSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задана неверная роль пользователя..
        /// </summary>
        internal static string InvalidUserRole {
            get {
                return ResourceManager.GetString("InvalidUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не найден..
        /// </summary>
        internal static string ItemIsNotFound {
            get {
                return ResourceManager.GetString("ItemIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборка уже одобрена..
        /// </summary>
        internal static string LeadListAlreadyApproved {
            get {
                return ResourceManager.GetString("LeadListAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборка пуста..
        /// </summary>
        internal static string LeadListIsEmpty {
            get {
                return ResourceManager.GetString("LeadListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка, сообщение пустое..
        /// </summary>
        internal static string MessageIsNullOrEmpty {
            get {
                return ResourceManager.GetString("MessageIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель некорректна..
        /// </summary>
        internal static string ModelIsInvalid {
            get {
                return ResourceManager.GetString("ModelIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать по крайней мере одну цифру (&apos;0&apos; - &apos;9&apos;). Пароль должен быть не менее 8 символов. Пароль должен содержать по крайней мере один символ в нижнем регистре. (&apos;a&apos;- &apos;z&apos;). Пароль должен содержать по крайней мере один символ в верхнем регистре (&apos;A&apos; - &apos;Z&apos;)..
        /// </summary>
        internal static string PasswordValidationError {
            get {
                return ResourceManager.GetString("PasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ходе обработки базы номеров произошла ошибка..
        /// </summary>
        internal static string PhoneDatabaseHandlingError {
            get {
                return ResourceManager.GetString("PhoneDatabaseHandlingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный номер телефона уже находится в стоп-листе..
        /// </summary>
        internal static string PhoneNumberIsAlreadyInStopList {
            get {
                return ResourceManager.GetString("PhoneNumberIsAlreadyInStopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали телефонный номер. .
        /// </summary>
        internal static string PhoneNumberIsEmpty {
            get {
                return ResourceManager.GetString("PhoneNumberIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с номерами пикселей неверен, номер пикселя или URL-адрес сайта встречаются более одного раза..
        /// </summary>
        internal static string PixelNumbersFileIsIncorrect {
            get {
                return ResourceManager.GetString("PixelNumbersFileIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект не найден..
        /// </summary>
        internal static string ProjectIsNotFound {
            get {
                return ResourceManager.GetString("ProjectIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен лимит проектов..
        /// </summary>
        internal static string ProjectsLimit {
            get {
                return ResourceManager.GetString("ProjectsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставщик не найден..
        /// </summary>
        internal static string ProviderIsNotFound {
            get {
                return ResourceManager.GetString("ProviderIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен лимит поставщиков..
        /// </summary>
        internal static string ProvidersLimit {
            get {
                return ResourceManager.GetString("ProvidersLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали адрес сайта. Заполните это поле и попробуйте снова..
        /// </summary>
        internal static string RetroDataUrlIsNullOrEmpty {
            get {
                return ResourceManager.GetString("RetroDataUrlIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен лимит статусов..
        /// </summary>
        internal static string StatusesLimit {
            get {
                return ResourceManager.GetString("StatusesLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус не задан..
        /// </summary>
        internal static string StatusIsEmpty {
            get {
                return ResourceManager.GetString("StatusIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный клиент не зарегистрирован в системе..
        /// </summary>
        internal static string SuchClientIsNotRegistred {
            get {
                return ResourceManager.GetString("SuchClientIsNotRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл, который вы пытаетесь прикрепить, не загружен в систему..
        /// </summary>
        internal static string SuchFileIsNotUploaded {
            get {
                return ResourceManager.GetString("SuchFileIsNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интерес с таким названием уже существует в системе..
        /// </summary>
        internal static string SuchInterestNameIsAlreadyExist {
            get {
                return ResourceManager.GetString("SuchInterestNameIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При приостановке проекта, вы должны заполнить причина по которой это произошло..
        /// </summary>
        internal static string SuspenseReasonMustBeFilled {
            get {
                return ResourceManager.GetString("SuspenseReasonMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество не может быть отрицательным..
        /// </summary>
        internal static string TheQuantityCanNotBeNegative {
            get {
                return ResourceManager.GetString("TheQuantityCanNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта функция устарела и не работает..
        /// </summary>
        internal static string ThisFunctionIsOutdatedAndNotWorking {
            get {
                return ResourceManager.GetString("ThisFunctionIsOutdatedAndNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальное значение больше конечного..
        /// </summary>
        internal static string UpBoundBiggerThanDownBound {
            get {
                return ResourceManager.GetString("UpBoundBiggerThanDownBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл, который вы пытаетесь загрузить имеет слишком большой размер. Максимальный допустимый размер - 20 мб..
        /// </summary>
        internal static string UploadFileIsLarge {
            get {
                return ResourceManager.GetString("UploadFileIsLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Временной интервал периода реализации проекта заполнен некорректно..
        /// </summary>
        internal static string WrongDateTimeInterval {
            get {
                return ResourceManager.GetString("WrongDateTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Временной интервал для рабочего дня указан некорректно..
        /// </summary>
        internal static string WrongScheduleTimeInterval {
            get {
                return ResourceManager.GetString("WrongScheduleTimeInterval", resourceCulture);
            }
        }
    }
}
